on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_LOCATION:
        required: true
      AZURE_SUFFIX:
        required: true
      AZURE_ADMIN_USERNAME:
        required: true
      AZURE_ADMIN_PASSWORD:
        required: true

jobs:
  validate:
    name: Validate Environment Secrets
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:          
      - run: |
          echo "Running on environment ${{ inputs.environment }}"
          if [ "${{ secrets.AZURE_CREDENTIALS }}" == "" ]; then
            echo "Please set environment secret 'AZURE_CREDENTIALS' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_LOCATION }}" == "" ]; then
            echo "Please set environment secret 'AZURE_LOCATION' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_SUFFIX }}" == "" ]; then
            echo "Please set environment secret 'AZURE_SUFFIX' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_ADMIN_USERNAME }}" == "" ]; then
            echo "Please set environment secret 'AZURE_ADMIN_USERNAME' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_ADMIN_PASSWORD }}" == "" ]; then
            echo "Please set environment secret 'AZURE_ADMIN_PASSWORD' before running this workflow"
            exit 1
          fi
